# Generated by Django 4.0.3 on 2022-04-09 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(max_length=128, unique=True)),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('race_and_ethnicity', models.SmallIntegerField(choices=[(0, 'Asian'), (1, 'American Indian or Alaska Nativ'), (2, 'Black or African American'), (3, 'Hispanic or Latino'), (4, 'Native Hawaiian or Other Pacific Islander'), (5, 'White')])),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CT_platform.drug')),
                ('patient_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_cohort', models.SmallIntegerField(default=20)),
                ('therapy_duration', models.SmallIntegerField(default=70)),
                ('visits_frequency', models.SmallIntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CT_platform.patients')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('onset', models.DateField()),
                ('end', models.DateField(null=True)),
                ('ae_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CT_platform.studyscheme'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(null=True)),
                ('ogtt', models.FloatField(null=True)),
                ('discontinuation', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CT_platform.patients')),
                ('visit_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related_ae', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CT_platform.adverseevent')),
            ],
        ),
    ]
