# Generated by Django 4.0.3 on 2022-04-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
