# Generated by Django 4.0.3 on 2022-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0002_alter_adverseevent_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ManyToManyField(to='CT_platform.patients'),
        ),
    ]
