# Generated by Django 4.0.3 on 2022-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0002_rename_treatment_patients_study_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=3),
        ),
    ]
