# Generated by Django 4.0.3 on 2022-04-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0003_remove_visit_patient_visit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CT_platform.patients'),
            preserve_default=False,
        ),
    ]
