# Generated by Django 4.0.3 on 2022-04-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0004_rename_visit_author_visit_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='related_ae',
            new_name='related_adverse_event',
        ),
    ]
