# Generated by Django 4.0.3 on 2022-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0005_rename_related_ae_visit_related_adverse_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyscheme',
            name='name',
            field=models.CharField(default='Treatment_arm_1', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='ogtt',
            field=models.FloatField(default=23.1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.FloatField(default=75),
            preserve_default=False,
        ),
    ]
