# Generated by Django 4.0.3 on 2022-04-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CT_platform', '0006_studyscheme_name_alter_visit_ogtt_alter_visit_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adverseevent',
            old_name='ae_author',
            new_name='author',
        ),
    ]
